# Server Port
server.port=8080
spring.application.name=gradepilot-backend

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/gradepilot_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Nandhu@552
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=GradePilotAISecretKey2026VeryLongSecureKeyForJWTSigningPurposes1234567890ABCDEF
app.jwt.expiration=86400000

# Logging
logging.level.com.gradepilot=DEBUG
logging.level.org.springframework.security=INFO

# Gemini API Configuration
app.gemini.api-key=AQ.Ab8RN6LlnWJb79bXi4McQh3z3quOCPHgKTnqSN5k_I23Giw2EA

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=valar9019@gmail.com
spring.mail.password=boyr sxer coxu xcfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

